/**
 * Saved client / company names for invoice "Bill to" quick-pick.
 * Edit this list as your roster changes.
 */
export const KNOWN_CLIENT_NAMES: readonly string[] = [
  "4AM Media",
  "A7 Global Tech LLP",
  "A7 Gtech - 2 Hostings",
  "Alliance Square",
  "Cafe - Chintu Friend",
  "Dronark - Pungi",
  "Epixable",
  "Epixable (Hospital)",
  "Heat Wave Media",
  "Jackfruit Technologies",
  "Jayanth - Paint",
  "Joanne Slaughter (363)",
  "Kannan Sirangapalli",
  "Kapila FAQ",
  "Kapila Management Software",
  "MTM FAQ",
  "Megha Signs Kodagu",
  "Panche Kattu",
  "Pixel Geek",
  "Powergate energy",
  "Pawan Refer - Krishna",
  "Rajans Poorvik Media",
  "RLS P",
  "Royal Passage",
  "Safe Wheels",
  "Sparkling Ads",
  "Spice Trip",
  "SS Foundation",
  "Sublime Camps",
  "TAH",
  "Texa",
  "Win Research Center",
  "Zach (Poland)",
].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: "base" }));
